version: '3.9'

services:
  db-postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_INIDB_DATABASE: flights-db
